name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      # Also covers warnings in test files, and lib compiled in the test environment
      - run: mix test --warnings-as-errors
      - run: mix site.fetch
      - run: mix site.build
